### ISSUE TITLE
Benchmark tests fail to run

### ISSUE THREAD

**Issue by YonatanKra** [material-components/material-components-web-components#1555]
**Describe the bug**
Following the steps in the contribution guide throws an error when running `npm run test:bench`

**To Reproduce**

1. Steps to reproduce the behavior:
2. git clone git@github.com:material-components/material-components-web-components.git mwc
3. cd mwc
4. npm install
5. npm run build
6. npm run test:bench

**Expected behavior**
I'd expect the script to run and allow me to benchmark.

**Screenshots**
![image](https://user-images.githubusercontent.com/6459899/88190963-99986d00-cc43-11ea-9aca-0998b61d977b.png)

**Browser Version (please complete the following information):**
 - OS: MacOS

**Additional context**
I get the following stack trace:
```
(node:14802) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'test/benchmark'
    at Object.readdirSync (fs.js:948:3)
    at /Users/ykra/projects/material-components-web-components/test/src/benchmark/cli.ts:113:16
    at Object.<anonymous> (/Users/ykra/projects/material-components-web-components/test/src/benchmark/cli.ts:162:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by e111077** [comment]
I cannot reproduce. Can you confirm that you are passing a parameter to the test:bench script. e.g.:

`npm run test:bench -- --package button`

**Comment by YonatanKra** [comment]
My bad 
Didn't notice the need for a package
Thanks :)
