### ISSUE TITLE
Cannot build.

### ISSUE THREAD

**Issue by rainerlopez** [material-components/material-components-web-components#177]
Following instructions to build master (as of today)
`git clone`
`npm run bootstrap`

fails with (npm log)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/home/rage/.npm-global/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bootstrap' ]
2 info using npm@6.5.0
3 info using node@v8.15.0
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle material-components-web-components@~prebootstrap: material-components-web-components@
6 info lifecycle material-components-web-components@~bootstrap: material-components-web-components@
7 verbose lifecycle material-components-web-components@~bootstrap: unsafe-perm in lifecycle true
8 verbose lifecycle material-components-web-components@~bootstrap: PATH: /home/rage/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/rage/Documents/Polymer/material-components-web-components/node_modules/.bin:/home/rage/.npm-global/bin:/home/rage/bin:/home/rage/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle material-components-web-components@~bootstrap: CWD: /home/rage/Documents/Polymer/material-components-web-components
10 silly lifecycle material-components-web-components@~bootstrap: Args: [ '-c',
10 silly lifecycle   'npm install && ./scripts/bootstrap.sh && npm run build' ]
11 silly lifecycle material-components-web-components@~bootstrap: Returned: code: 1  signal: null
12 info lifecycle material-components-web-components@~bootstrap: Failed to exec bootstrap script
13 verbose stack Error: material-components-web-components@ bootstrap: `npm install && ./scripts/bootstrap.sh && npm run build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/rage/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/rage/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid material-components-web-components@
15 verbose cwd /home/rage/Documents/Polymer/material-components-web-components
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/bin/node" "/home/rage/.npm-global/bin/npm" "run" "bootstrap"
18 verbose node v8.15.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error material-components-web-components@ bootstrap: `npm install && ./scripts/bootstrap.sh && npm run build`
22 error Exit status 1
23 error Failed at the material-components-web-components@ bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any help would be appreciated.
Thanks.

**Comment by straversi** [comment]
I see that right now the package build order does not check dependencies, which is causing errors on first build, e.g. 'cannot build tab because tab-indicator does not exist'. Thanks for creating the issue.

**Comment by frankiefu** [comment]
Just ran a fresh clone and build and it worked fine.
```
> git clone git@github.com:material-components/material-components-web-components.git
> npm run bootstrap
```
Closing this now but please let us know if you are still having issue.

**Comment by JustinXinLiu** [comment]
I just did a clean clone and got the same error.

**Comment by JustinXinLiu** [comment]
Apologies, after I set up wsl on my Windows machine, it now builds fine.

**Comment by frankiefu** [comment]
Thanks for the report.
