### ISSUE TITLE
Build Errors on Clean Checkout

### ISSUE THREAD

**Issue by woodrowbarlow** [material-components/material-components-web-components#2498]
**Describe the bug**

Attempting to build the current version of master (b62f901d09efbc84cd44bfdae7feba0601e2a0c2) based on the instructions in the "Contributing" section of the README results in build errors.

Am I missing a step?

**To Reproduce**

Dockerfile:

```
FROM node:lts-alpine
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build
```

```
> [5/5] RUN npm run build:
#9 0.813
#9 0.813 > material-components-web-components@ build /app
#9 0.813 > npm run build:styling && npm run build:typescript -- --verbose
#9 0.813
#9 1.084
#9 1.084 > material-components-web-components@ build:styling /app
#9 1.084 > lerna run --stream build:style
#9 1.084
#9 1.525 lerna notice cli v3.22.1
#9 1.646 lerna info Executing command in 30 packages: "npm run build:style"
#9 1.672 lerna WARN ECYCLE Dependency cycles detected, you should fix these!
#9 1.672 lerna WARN ECYCLE @material/mwc-list -> @material/mwc-menu -> @material/mwc-list
#9 2.126 @material/mwc-circular-progress: > @material/mwc-circular-progress@0.21.0 build:style /app/packages/circular-progress
#9 2.126 @material/mwc-circular-progress: > node ../../scripts/sass-to-lit-css/index.js mwc-circular-progress.scss
#9 2.166 @material/mwc-elevation-overlay: > @material/mwc-elevation-overlay@0.21.0 build:style /app/packages/elevation-overlay
#9 2.166 @material/mwc-elevation-overlay: > node ../../scripts/sass-to-lit-css/index.js mwc-elevation-overlay.scss
#9 2.424 @material/mwc-icon: > @material/mwc-icon@0.21.0 build:style /app/packages/icon
#9 2.425 @material/mwc-icon: > node ../../scripts/sass-to-lit-css/index.js mwc-icon-host.scss
#9 2.428 @material/mwc-linear-progress: > @material/mwc-linear-progress@0.21.0 build:style /app/packages/linear-progress
#9 2.428 @material/mwc-linear-progress: > node ../../scripts/sass-to-lit-css/index.js mwc-linear-progress.scss
#9 2.434 @material/mwc-drawer: > @material/mwc-drawer@0.21.0 build:style /app/packages/drawer
#9 2.434 @material/mwc-drawer: > node ../../scripts/sass-to-lit-css/index.js mwc-drawer.scss
#9 2.437 @material/mwc-floating-label: > @material/mwc-floating-label@0.21.0 build:style /app/packages/floating-label
#9 2.437 @material/mwc-floating-label: > node ../../scripts/sass-to-lit-css/index.js mwc-floating-label.scss
#9 4.938 @material/mwc-line-ripple: > @material/mwc-line-ripple@0.21.0 build:style /app/packages/line-ripple
#9 4.938 @material/mwc-line-ripple: > node ../../scripts/sass-to-lit-css/index.js mwc-line-ripple.scss
#9 4.970 @material/mwc-notched-outline: > @material/mwc-notched-outline@0.21.0 build:style /app/packages/notched-outline
#9 4.970 @material/mwc-notched-outline: > node ../../scripts/sass-to-lit-css/index.js mwc-notched-outline.scss
#9 5.028 @material/mwc-floating-label: /app/node_modules/node-sass-import/lib/node-sass-import.js:82
#9 5.028 @material/mwc-floating-label:             if (err) throw err;
#9 5.028 @material/mwc-floating-label:                      ^
#9 5.028 @material/mwc-floating-label: Error: Cannot find module '@material/animation/_index.scss' from '/app/packages/floating-label'
#9 5.028 @material/mwc-floating-label:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:48:31
#9 5.028 @material/mwc-floating-label:     at processDirs (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:182:39)
#9 5.029 @material/mwc-floating-label:     at ondir (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:197:13)
#9 5.029 @material/mwc-floating-label:     at load (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:80:43)
#9 5.029 @material/mwc-floating-label:     at onex (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:105:17)
#9 5.029 @material/mwc-floating-label:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:26:73
#9 5.029 @material/mwc-floating-label:     at FSReqCallback.oncomplete (fs.js:192:21) {
#9 5.029 @material/mwc-floating-label:   code: 'MODULE_NOT_FOUND'
#9 5.029 @material/mwc-floating-label: }
#9 5.040 @material/mwc-drawer: /app/node_modules/node-sass-import/lib/node-sass-import.js:82
#9 5.040 @material/mwc-drawer:             if (err) throw err;
#9 5.040 @material/mwc-drawer:                      ^
#9 5.040 @material/mwc-drawer: Error: Cannot find module '@material/drawer/_index.scss' from '/app/packages/drawer'
#9 5.040 @material/mwc-drawer:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:48:31
#9 5.040 @material/mwc-drawer:     at processDirs (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:182:39)
#9 5.041 @material/mwc-drawer:     at ondir (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:197:13)
#9 5.041 @material/mwc-drawer:     at load (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:80:43)
#9 5.041 @material/mwc-drawer:     at onex (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:105:17)
#9 5.041 @material/mwc-drawer:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:26:73
#9 5.041 @material/mwc-drawer:     at FSReqCallback.oncomplete (fs.js:192:21) {
#9 5.041 @material/mwc-drawer:   code: 'MODULE_NOT_FOUND'
#9 5.041 @material/mwc-drawer: }
#9 5.047 @material/mwc-circular-progress: /app/node_modules/node-sass-import/lib/node-sass-import.js:82
#9 5.047 @material/mwc-circular-progress:             if (err) throw err;
#9 5.047 @material/mwc-circular-progress:                      ^
#9 5.047 @material/mwc-circular-progress: Error: Cannot find module '@material/theme/custom-properties' from '/app/packages/circular-progress'
#9 5.047 @material/mwc-circular-progress:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:48:31
#9 5.047 @material/mwc-circular-progress:     at processDirs (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:182:39)
#9 5.048 @material/mwc-circular-progress:     at ondir (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:197:13)
#9 5.048 @material/mwc-circular-progress:     at load (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:80:43)
#9 5.048 @material/mwc-circular-progress:     at onex (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:105:17)
#9 5.048 @material/mwc-circular-progress:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:26:73
#9 5.048 @material/mwc-circular-progress:     at FSReqCallback.oncomplete (fs.js:192:21) {
#9 5.048 @material/mwc-circular-progress:   code: 'MODULE_NOT_FOUND'
#9 5.048 @material/mwc-circular-progress: }
#9 5.050 @material/mwc-floating-label: npm ERR! code ELIFECYCLE
#9 5.050 @material/mwc-floating-label: npm ERR! errno 1
#9 5.051 @material/mwc-linear-progress: /app/node_modules/node-sass-import/lib/node-sass-import.js:82
#9 5.051 @material/mwc-linear-progress:             if (err) throw err;
#9 5.051 @material/mwc-linear-progress:                      ^
#9 5.051 @material/mwc-linear-progress: Error: Cannot find module '@material/theme/custom-properties' from '/app/packages/linear-progress'
#9 5.055 @material/mwc-linear-progress:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:48:31
#9 5.056 @material/mwc-linear-progress:     at processDirs (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:182:39)
#9 5.056 @material/mwc-linear-progress:     at ondir (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:197:13)
#9 5.056 @material/mwc-linear-progress:     at load (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:80:43)
#9 5.057 @material/mwc-linear-progress:     at onex (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:105:17)
#9 5.057 @material/mwc-linear-progress:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:26:73
#9 5.057 @material/mwc-linear-progress:     at FSReqCallback.oncomplete (fs.js:192:21) {
#9 5.057 @material/mwc-linear-progress:   code: 'MODULE_NOT_FOUND'
#9 5.058 @material/mwc-linear-progress: }
#9 5.058 @material/mwc-floating-label: npm ERR! @material/mwc-floating-label@0.21.0 build:style: `node ../../scripts/sass-to-lit-css/index.js mwc-floating-label.scss`
#9 5.059 @material/mwc-floating-label: npm ERR! Exit status 1
#9 5.059 @material/mwc-floating-label: npm ERR!
#9 5.060 @material/mwc-floating-label: npm ERR! Failed at the @material/mwc-floating-label@0.21.0 build:style script.
#9 5.060 @material/mwc-floating-label: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 5.063 @material/mwc-circular-progress: npm ERR! code ELIFECYCLE
#9 5.064 @material/mwc-circular-progress: npm ERR! errno 1
#9 5.064 @material/mwc-drawer: npm ERR! code ELIFECYCLE
#9 5.069 @material/mwc-drawer: npm ERR! errno 1
#9 5.069 @material/mwc-floating-label: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
#9 5.069 @material/mwc-floating-label: npm ERR! A complete log of this run can be found in:
#9 5.069 @material/mwc-floating-label: npm ERR!     /root/.npm/_logs/2021-06-28T12_16_06_847Z-debug.log
#9 5.073 @material/mwc-drawer: npm ERR! @material/mwc-drawer@0.21.0 build:style: `node ../../scripts/sass-to-lit-css/index.js mwc-drawer.scss`
#9 5.074 @material/mwc-drawer: npm ERR! Exit status 1
#9 5.074 @material/mwc-drawer: npm ERR!
#9 5.074 @material/mwc-drawer: npm ERR! Failed at the @material/mwc-drawer@0.21.0 build:style script.
#9 5.074 @material/mwc-drawer: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 5.074 @material/mwc-circular-progress: npm ERR! @material/mwc-circular-progress@0.21.0 build:style: `node ../../scripts/sass-to-lit-css/index.js mwc-circular-progress.scss`
#9 5.075 @material/mwc-circular-progress: npm ERR! Exit status 1
#9 5.075 @material/mwc-circular-progress: npm ERR!
#9 5.075 @material/mwc-circular-progress: npm ERR! Failed at the @material/mwc-circular-progress@0.21.0 build:style script.
#9 5.075 @material/mwc-circular-progress: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 5.076 @material/mwc-elevation-overlay: /app/node_modules/node-sass-import/lib/node-sass-import.js:82
#9 5.076 @material/mwc-elevation-overlay:             if (err) throw err;
#9 5.077 @material/mwc-elevation-overlay:                      ^
#9 5.077 @material/mwc-elevation-overlay: Error: Cannot find module '@material/elevation/elevation-theme' from '/app/packages/elevation-overlay'
#9 5.077 @material/mwc-elevation-overlay:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:48:31
#9 5.077 @material/mwc-elevation-overlay:     at processDirs (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:182:39)
#9 5.077 @material/mwc-elevation-overlay:     at ondir (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:197:13)
#9 5.078 @material/mwc-elevation-overlay:     at load (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:80:43)
#9 5.078 @material/mwc-elevation-overlay:     at onex (/app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:105:17)
#9 5.078 @material/mwc-elevation-overlay:     at /app/node_modules/node-sass-import/node_modules/resolve/lib/async.js:26:73
#9 5.078 @material/mwc-elevation-overlay:     at FSReqCallback.oncomplete (fs.js:192:21) {
#9 5.078 @material/mwc-elevation-overlay:   code: 'MODULE_NOT_FOUND'
#9 5.078 @material/mwc-elevation-overlay: }
#9 5.083 @material/mwc-linear-progress: npm ERR! code ELIFECYCLE
#9 5.083 @material/mwc-linear-progress: npm ERR! errno 1
#9 5.093 lerna ERR! npm run build:style exited 1 in '@material/mwc-floating-label'
#9 5.094 lerna WARN complete Waiting for 8 child processes to exit. CTRL-C to exit immediately.
#9 5.105 npm ERR! code ELIFECYCLE
#9 5.105 npm ERR! errno 1
#9 5.109 npm ERR! material-components-web-components@ build:styling: `lerna run --stream build:style`
#9 5.110 npm ERR! Exit status 1
#9 5.110 npm ERR!
#9 5.110 npm ERR! Failed at the material-components-web-components@ build:styling script.
#9 5.110 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 5.950
#9 5.950 npm ERR! A complete log of this run can be found in:
#9 5.950 npm ERR!     /root/.npm/_logs/2021-06-28T12_16_06_901Z-debug.log
#9 5.959 npm ERR! code ELIFECYCLE
#9 5.959 npm ERR! errno 1
#9 5.964 npm ERR! material-components-web-components@ build: `npm run build:styling && npm run build:typescript -- --verbose`
#9 5.964 npm ERR! Exit status 1
#9 5.964 npm ERR!
#9 5.964 npm ERR! Failed at the material-components-web-components@ build script.
#9 5.964 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 5.972
#9 5.972 npm ERR! A complete log of this run can be found in:
#9 5.972 npm ERR!     /root/.npm/_logs/2021-06-28T12_16_07_755Z-debug.log
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
```

**Expected behavior**
The build completes successfully (return code 0 from `npm run build`).

**Comment by woodrowbarlow** [comment]
Aha! The bootstrap script is a bash script. alpine (and mac os, the other environment I tried) doesn't have bash by default.

```
/mwc # npm run bootstrap

> material-components-web-components@ bootstrap /mwc
> ./scripts/bootstrap.sh

env: can't execute 'bash': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! material-components-web-components@ bootstrap: `./scripts/bootstrap.sh`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the material-components-web-components@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-29T13_03_48_266Z-debug.log
```

Using `FROM node:lts` (non-alpine) got me running. Maybe the readme should highlight the dependence on bash, or, if possible, the scripts could use the `#!/bin/sh` shebang?

**Comment by asyncLiz** [comment]
At the moment for dev environments we require bash to be available. This may no longer be a problem in the future if the bootstrap.sh script is removed though!

**Comment by youbet1980** [comment]
> Using `FROM node:lts` (non-alpine) got me running. Maybe the readme should highlight the dependence on bash, or, if possible, the scripts could use the `#!/bin/sh` shebang?

How did you do this on your mac terminal? eg. What command did you run in terminal instead of
npm install
npm run build
